name: 'SBOM Predicate'
description: 'Generate reference predicate for SBOM attestations'
author: 'GitHub'

inputs:
  sbom-path:
    description: >
      Path to the SBOM file to generate reference predicate
    required: true
  github-token:
    description: >
      The GitHub token used to upload the SBOM to a release
    required: true
outputs:
  predicate-path:
    description: >
      The path to the JSON-serialized of the attestation predicate
  predicate-type:
    description: >
      URI identifying the type of the predicate.
runs:
  using: node24
  main: ../dist/index.js
